mock

diff --git a/.github/workflows/mock.yml b/.github/workflows/mock.yml
--- a/.github/workflows/mock.yml
+++ b/.github/workflows/mock.yml
@@ -32,4 +32,5 @@ jobs:
     steps:
       - id: output-step
         run: |
-          echo "Job one succeeded ✅"
+          echo "Job two failed ❌"
+          exit 1
