add test command

diff --git a/.github/workflows/test-model-image.yml b/.github/workflows/test-model-image.yml
--- a/.github/workflows/test-model-image.yml
+++ b/.github/workflows/test-model-image.yml
@@ -32,14 +32,36 @@ jobs:
           MODEL_ID: ${{ inputs.repo_name }}
         run: |
           conda run -n base bash -c "
-            ersilia -v fetch $MODEL_ID --from_dockerhub --version dev-amd64 &&
-            ersilia serve $MODEL_ID &&
-            ersilia example -f input.csv -n 3 &&
-            ersilia run -i input.csv -o output.csv &&
-            ersilia close &&
-            ersilia delete $MODEL_ID &&
-            head output.csv
+            ersilia -v test $MODEL_ID --deep --from_dockerhub --version dev-amd64
           "
+      - name: Parse test results
+        env:
+          MODEL_ID: ${{ inputs.repo_name }}
+        run: |
+          TEST_JSON="${MODEL_ID}-test-deep.json"
+          
+          if [[ ! -f "$TEST_JSON" ]]; then
+            echo "Error: Test results file $TEST_JSON not found!"
+            exit 1
+          fi
+          mv "${MODEL_ID}-test-deep.json" "${MODEL_ID}-test-deep-amd64.json"
+          TEST_JSON="${MODEL_ID}-test-deep-amd64.json"
+          echo "Parsing test results from $TEST_JSON"
+
+          TEST_FAILED=$(jq 'recurse | objects | select(map(select(. == false)) | length > 0)' "$TEST_JSON")
+              if [[ -n "$TEST_FAILED" ]]; then
+                echo "❌ Some tests failed. Stopping workflow."
+                exit 1
+              fi
+
+      - name: Upload logs as artifacts
+        uses: actions/upload-artifact@v4
+        env:
+          MODEL_ID: ${{ inputs.repo_name }}
+        with:
+          name: test-report-amd64
+          path: |
+            ${MODEL_ID}-test-deep-amd64.json
 
   test-image-arm64:
     runs-on: default-linux-arm64
@@ -63,14 +85,36 @@ jobs:
         env:
           MODEL_ID: ${{ inputs.repo_name }}
         run: |
-          conda run -n base ersilia -v fetch $MODEL_ID --from_dockerhub --version dev-arm64 2>&1 | tee fetch.log
+          conda run -n base ersilia -v test $MODEL_ID --deep --from_dockerhub --version dev-arm64 2>&1 | tee fetch.log
+
+      - name: Parse test results
+        env:
+          MODEL_ID: ${{ inputs.repo_name }}
+        run: |
+          TEST_JSON="${MODEL_ID}-test-deep.json"
+          
+          if [[ ! -f "$TEST_JSON" ]]; then
+            echo "Error: Test results file $TEST_JSON not found!"
+            exit 1
+          fi
+          mv "${MODEL_ID}-test-deep.json" "${MODEL_ID}-test-deep-arm64.json"
+          TEST_JSON="${MODEL_ID}-test-deep-arm64.json"
+          echo "Parsing test results from $TEST_JSON"
+
+          TEST_FAILED=$(jq 'recurse | objects | select(map(select(. == false)) | length > 0)' "$TEST_JSON")
+              if [[ -n "$TEST_FAILED" ]]; then
+                echo "❌ Some tests failed. Stopping workflow."
+                exit 1
+              fi
         
       - name: Upload logs as artifacts
         uses: actions/upload-artifact@v4
+        env:
+          MODEL_ID: ${{ inputs.repo_name }}
         with:
-          name: ersilia-logs
+          name: test-report-arm64
           path: |
-            fetch.log
+            ${MODEL_ID}-test-deep-arm64.json
       
   retag-image:
     runs-on: ubuntu-latest
diff --git a/.github/workflows/test-model-source.yml b/.github/workflows/test-model-source.yml
--- a/.github/workflows/test-model-source.yml
+++ b/.github/workflows/test-model-source.yml
@@ -154,26 +154,52 @@ jobs:
           repository: "ersilia-os/${{ github.event.repository.name }}"
           github_token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Fetch model and run #TODO change for test command 
+      - name: Fetch model and run
         env:
           MODEL_ID: ${{ inputs.repo_name }}
         run: |
           conda run -n base bash -c "
-            ersilia -v fetch $MODEL_ID --from_github &&
-            ersilia serve $MODEL_ID &&
-            ersilia example -f input.csv -n 3 &&
-            ersilia run -i input.csv -o output.csv &&
-            ersilia close &&
-            ersilia delete $MODEL_ID &&
-            head output.csv
+            ersilia -v test $MODEL_ID --shallow --from_github
           "
 
-      - name: Upload log output
+      - name: Parse test results
+        env:
+          MODEL_ID: ${{ inputs.repo_name }}
+        run: |
+          TEST_JSON="${MODEL_ID}-test-shallow.json"
+
+          if [[ ! -f "$TEST_JSON" ]]; then
+            echo "Error: Test results file $TEST_JSON not found!"
+            exit 1
+          fi
+
+          echo "Parsing test results from $TEST_JSON"
+
+          
+          TEST_FAILED=$(jq 'recurse | objects | select(map(select(. == false)) | length > 0)' "$TEST_JSON")
+              if [[ -n "$TEST_FAILED" ]]; then
+                echo "❌ Some tests failed. Stopping workflow."
+                exit 1
+              fi
+
+          ENV_SIZE=$(jq '.model_size_check.environment_size_mb' "$TEST_JSON")
+          DIR_SIZE=$(jq '.model_size_check.directory_size_mb' "$TEST_JSON")
+          echo "Environment size: $ENV_SIZE MB"
+          echo "Directory size: $DIR_SIZE MB"
+          echo "Environment size (MB): $ENV_SIZE" > model_sizes.txt
+          echo "Directory size (MB): $DIR_SIZE" >> model_sizes.txt
+          cat model_sizes.txt
+
+      - name: Upload files
         if: always()
         uses: actions/upload-artifact@v4.5.0
+        env:
+          MODEL_ID: ${{ inputs.repo_name }}
         with:
-          name: debug-logs
+          name: logs
           retention-days: 14
           path: |
             /home/runner/eos/*.log
             ./*.log
+            $MODEL_ID-test-shallow.json
+            model_sizes.txt
diff --git a/.github/workflows/upload-model-to-s3.yml b/.github/workflows/upload-model-to-s3.yml
--- a/.github/workflows/upload-model-to-s3.yml
+++ b/.github/workflows/upload-model-to-s3.yml
@@ -43,6 +43,31 @@ jobs:
           conda run -n base git-lfs install
           conda run -n base python -m pip install git+https://github.com/ersilia-os/ersilia.git
 
+      - name: Download model sizes
+        uses: actions/download-artifact@v4
+        with:
+          name: logs
+          path: .
+
+      - name: Read model sizes
+        run: |
+          if [[ ! -f ./model_sizes.txt ]]; then
+            echo "Error: model_sizes.txt not found!"
+            exit 1
+          fi
+
+          ENV_SIZE=$(grep "Environment size" ./model_sizes.txt | awk -F': ' '{print $2}')
+          DIR_SIZE=$(grep "Directory size" ./model_sizes.txt | awk -F': ' '{print $2}')
+
+          if [[ -z "$ENV_SIZE" || -z "$DIR_SIZE" ]]; then
+            echo "Error: Missing environment size or directory size."
+            exit 1
+          fi
+          echo "Environment Size (MB): $ENV_SIZE"
+          echo "Directory Size (MB): $DIR_SIZE"
+          echo "ENVIRONMENT_SIZE_MB=$ENV_SIZE" >> $GITHUB_ENV
+          echo "DIRECTORY_SIZE_MB=$DIR_SIZE" >> $GITHUB_ENV
+
       - name: Check metadata file
         id: checkMetadata
         continue-on-error: true
@@ -60,6 +85,8 @@ jobs:
           with open('metadata.json', 'r') as f:
              data = json.load(f)
           data['S3'] = 'https://ersilia-models-zipped.s3.eu-central-1.amazonaws.com/{0}.zip'.format(data['Identifier'])
+          data["Model Size"] = ${{ DIRECTORY_SIZE_MB }}
+          data["Environment Size"] = ${{ env.ENVIRONMENT_SIZE_MB }}
           with open('metadata.json', 'w') as f:
              json.dump(data, f, indent=4)
           "
@@ -72,6 +99,8 @@ jobs:
           with open('metadata.yml', 'r') as f:
              data = yaml.safe_load(f)
           data['S3'] = 'https://ersilia-models-zipped.s3.eu-central-1.amazonaws.com/{0}.zip'.format(data['Identifier'])
+          data["Model Size"] = ${{ DIRECTORY_SIZE_MB }}
+          data["Environment Size"] = ${{ env.ENVIRONMENT_SIZE_MB }}
           with open('metadata.yml', 'w') as f:
              yaml.dump(data, f, default_flow_style=False, sort_keys=False)
           "
