separate actions on push

diff --git a/.github/workflows/test-model-source.yml b/.github/workflows/test-model-source.yml
--- a/.github/workflows/test-model-source.yml
+++ b/.github/workflows/test-model-source.yml
@@ -23,7 +23,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
-
+      #TODO reinstate Free Disk Space
       - uses: actions/checkout@v4.2.2
         with:
           lfs: true
@@ -40,6 +40,38 @@ jobs:
           conda run -n base conda install gh -c conda-forge
           conda run -n base python -m pip install 'git+https://github.com/ersilia-os/ersilia.git#egg=ersilia[test]'
 
+      - name: Select correct metadata file
+        run: |
+          if [ -f "metadata.yml" ]; then
+            metadata="metadata.yml"
+          elif [ -f "metadata.json" ]; then
+            metadata="metadata.json"
+          else
+            echo "No metadata file found."
+            exit 1
+          fi
+          echo "METADATA_FILE=$metadata" >> "$GITHUB_ENV"
+          echo "Found metadata file: $metadata"
+
+      - name: Decide metadata upate to/from Airtable
+        run: |
+          if [[ "$METADATA_FILE" == "metadata.json" ]]; then
+            output_consistency=$(jq -r '.["Output Consistency"] // empty' "$METADATA_FILE")
+          elif [[ "$METADATA_FILE" == "metadata.yml" ]]; then
+            output_consistency=$(yq e '.["Output Consistency"] // ""' "$METADATA_FILE")
+          fi
+
+          if [ -n "$output_consistency" ]; then
+            echo "'Output Consistency' exists and has value: $output_consistency"
+            echo "Updating metadata **TO** Airtable."
+            echo "AIRTABLE_ACTION=TO" >> "$GITHUB_ENV"
+          else
+            echo "'Output Consistency' is missing or empty in $METADATA_FILE."
+            echo "Updating metadata **FROM** Airtable."
+            echo "AIRTABLE_ACTION=FROM" >> "$GITHUB_ENV"
+          fi
+
+
       - name: Update metadata to or from AirTable
         env:
           USER_NAME: ${{ github.repository_owner }}
@@ -53,38 +85,14 @@ jobs:
           command: |
             set -e  # Ensure failure stops execution
             conda run -n base pip install requests pyairtable
-            
             wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/airtableops.py
             wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/readme_formatter.py
 
-            # check if we have a YAML or JSON file
-            if [ -f "metadata.yml" ]; then
-              metadata="metadata.yml"
-            elif [ -f "metadata.json" ]; then
-              metadata="metadata.json"
-            else
-              echo "No metadata file found."
-              exit 1
-            fi
 
-            echo "Found metadata file: $metadata"
-
-            # Check the "Output Consistency" field based on file type.
-            if [[ "$metadata" == "metadata.json" ]]; then
-              # Extract the "Output Consistency" field from JSON.
-              output_consistency=$(jq -r '.["Output Consistency"] // empty' "$metadata")
-            elif [[ "$metadata" == "metadata.yml" ]]; then
-              # Extract the "Output Consistency" field from YAML.
-              output_consistency=$(yq e '.["Output Consistency"] // ""' "$metadata")
-            fi
-
-            # Verify that the field exists and is non-empty.
-            if [ -n "$output_consistency" ]; then
-              echo "'Output Consistency' exists and has value: $output_consistency"
+            if [[ "$AIRTABLE_ACTION" == "TO" ]]; then
               echo "Updating metadata to AirTable looking at owner: $USER_NAME"
               conda run -n base python3 airtableops.py airtable-update --user $USER_NAME --repo $REPO_NAME --branch $BRANCH --api-key $AIRTABLE_API_KEY
-            else
-              echo "'Output Consistency' is missing or empty in $metadata."
+            if [[ "$AIRTABLE_ACTION" == "FROM" ]]; then
               echo "Updating metadata from AirTable looking at owner: $USER_NAME"
               conda run -n base python3 airtableops.py metadata-update --repo $REPO_NAME --path . --api-key $AIRTABLE_API_KEY
             fi
